spring.datasource:
  url:
  username:
  tomcat:
    maxActive: 10
    maxWait: 5
    initialSize: 2
    validationQuery: SELECT 1

security:
  key:
  cookieName: PERSISTENT
  securityCookie:
  tokenValiditySeconds: 31536000 # 1 year

wechat:
  appId:
  secret:
  token:
  aesKey:

dataPointValidToken: change me

qiniu:
  access:
  secret:

jcseg:
  lexiconPath: classpath:lexicon/lex-main.lex

luosimao.key:

lucene.directory: